#!/bin/bash

ACCESS_LOG_SSL=/var/log/apache2/access_ssl.log
URL_SSL=example.com
PORT_SSL=9871
OUTPUT_SSL=~/Projects/rtweb/index.html
TIME_FORMAT_SSL=%H:%M:%S
DATE_FORMAT_SSL=%d/%b/%y
LOG_FORMAT_SSL=COMBINED
SSL_CERT_2=/etc/apache2/ssl/rtweb-web-ffy-ch.crt
SSL_KEY_2=/etc/apache2/ssl/rtweb-ffy-ch.key

[ -f /etc/systemd/goaccess-report.conf ] && source /etc/systemd/goaccess-report.conf || true
ACCESS_LOG_SSL=$ACCESS_LOG_SSL
URL_SSL=$URL
OUTPUT_SSL=$OUTPUT
TIME_FORMAT_SSL=$TIME_FORMAT
DATE_FORMAT_SSL=$DATE_FORMAT
LOG_FORMAT_SSL=$LOG_FORMAT
SSL_CERT_2=$SSL_CERT_2
SSL_KEY_2=$SSL_KEY_2

goaccess -f $ACCESS_LOG_SSL -a -o $OUTPUT_SSL --real-time-html --html-report-title="Server Statistics - SSL" --ws-url=$URL_SSL --port=$PORT_SSL --ssl-cert=$SSL_CERT_2 --ssl-key=$SSL_KEY_2 --time-format=$TIME_FORMAT_SSL --date-format=$DATE_FORMAT_SSL --log-format=$LOG_FORMAT_SSL
